In [2]:
!pip install numpy

In [1]:
!pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 3.1 MB/s eta 0:00:00a 0:00:01


In [3]:
import numpy as np
import pandas as pd

In [4]:
a= np.array(2)
b = np.array([[1,5,4],[5,5,4]])
print(a.ndim)
print(b.shape)
print(b.size)

0
(2, 3)
6


In [ ]:
c= np.array([1,2,3],ndmin=1)
print(c.ndim)
print (c.shape)
print(c)

1
(3,)
[1 2 3]


In [ ]:
a = np.arange(15)
print(a.shape)

(15,)


In [ ]:
b = a.reshape(3,5)

In [ ]:
print("a is : ", a)
print("b is : ", b)
print("c is : ", c)

a is :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
b is :  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
c is :  [1 2 3]


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr1 = np.array([1,0,'abc'])
arr1

array(['1', '0', 'abc'], dtype='<U21')

In [ ]:
arr1.dtype

dtype('<U21')

In [ ]:
a = np.array([1,23,4])
print (a)
b= np.append(a, [6,88])
print (b)

[ 1 23  4]
[ 1 23  4  6 88]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.append(a,[[7,8,9]], axis = 0)
print (b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#a = np.array([[1,2,3],[4,5,6]])
c = np.append(b,[[8],[5], [5]], axis = 1)
print (c)

[[1 2 3 8]
 [4 5 6 5]
 [7 8 9 5]]


In [ ]:
a = np.array([55,88,45,87,55,54,54,55,88,85,99,12])
a.max()

99

In [ ]:
a.std()

20.922714928995234

In [ ]:
a.var()

437.76000000000005

In [ ]:
a.mean()

74.8

In [ ]:
np.median(a)

87.0

In [ ]:
a = np.array([55,88,45,87,55,54,54,55,88,85,99,12])
b= a.reshape(3,4)
print(b)

[[55 88 45 87]
 [55 54 54 55]
 [88 85 99 12]]


In [ ]:
a = np.arange(1,10)
b = a.reshape(3,3)
b.mean(axis = 1)

array([2., 5., 8.])

In [ ]:
np.random.seed(12)
a = np.random.randint(1,11,size = 1000)
b = np.random.randint(1,11,size = 123)
print(a.mean())
print(b.mean())

5.513
5.479674796747967


In [ ]:
arr = np.arange(15).reshape((3,5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
print(np.dot(arr,arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [ ]:
print(np.dot(arr.T,arr))

[[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]


In [ ]:
#import pandas as pd

In [ ]:
a = {['a': 55 ,'b' : 6, 'c' : 5]}
a[a]

SyntaxError: invalid syntax (<ipython-input-98-61311489d358>, line 1)

In [ ]:
ser2  = pd.Series([22,35,58],index = ['a', 'a', 'c'], name = 'age')
ser2

a    22
a    35
c    58
Name: age, dtype: int64

In [ ]:
ser2[2]

<ipython-input-108-fea5ca1ac2fd>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[2]


58

In [ ]:
dfi = pd.DataFrame({
    "Name": ["a", "b", "c", "d"],
    "Team": ["dsfsfdsd"]*4,
    "Number": [55,None, 66, 88]
})

print(dfi)

  Name      Team  Number
0    a  dsfsfdsd    55.0
1    b  dsfsfdsd     NaN
2    c  dsfsfdsd    66.0
3    d  dsfsfdsd    88.0


In [ ]:
dfi['Name']

0    a
1    b
2    c
3    d
Name: Name, dtype: object

In [ ]:
dfi.loc[2:800,"Name":"Number"]

Name      Team  Number
2    c  dsfsfdsd    66.0
3    d  dsfsfdsd    88.0